server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/materialsdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  jwt:
    secret: change-this-secret-in-production
    expiration-ms: 3600000
